# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install:
## Install a fixed version of ggplot2
- Rscript -e 'remove.packages("ggplot2")'
- wget http://cran.rstudio.com/src/contrib/Archive/RcppArmadillo/ggplot2_2.2.1.tar.gz
- R CMD INSTALL ggplot2_2.2.1.tar.gz
- rm -f ggplot2_2.2.1.tar.gz