devtools::use_data(KendallExactTable,
                   KendallQuantileTable,
                   KolmogorovTable,
                   KolmogorovTwoSample,
                   KolmogorovTwoSampleAsymptotic,
                   NMRanksLeft,
                   NMRanksRight,
                   PageTable,
                   PartialCorrelationTable,
                   RanksVonNeumann,
                   RunsUpDown,
                   SpearmanExactTable,
                   SpearmanQuantileTable,
                   TotalNumberOfRuns.Left,
                   TotalNumberOfRuns.Right,
                   WilcoxonRanksSumTable,
                   WilcoxonTable,
                   internal = TRUE,
                   overwrite = TRUE)
